ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
   	path('order/', include('order.urls')),
    path('account/', include('account.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
   
]



urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import cart_view, ChechoutProcess, PaymentView
app_name = 'order'

urlpatterns = [
		
			path('cart/',cart_view, name= 'cart_view' ),
			path('checkout/', ChechoutProcess.as_view(), name= 'checkout'),
			path('payment/',PaymentView.as_view(), name='stripe' )

		]

products/urls.py
from django.urls import path
from .views import (HomeListView, ProductDetailView, 
					add_to_cart, remove_from_cart,
					remove_single_product_from_cart,
					add_single_product_to_cart
					
					)
app_name = 'products'
urlpatterns = [

	path('', HomeListView.as_view(), name= 'home'),
	path('detail/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
   	path('add-to-cart/<slug:slug>/', add_to_cart, name= 'add-to-cart'),
   	path('remove-from-cart/<slug:slug>/', remove_from_cart, name= 'remove-from-cart'),
	path('remove-single-product-from-cart/<slug:slug>/', remove_single_product_from_cart, name= 'remove-single'),
	path('add-single-product-to-cart/<slug:slug>/', add_single_product_to_cart, name= 'add-single')

]

products/models.py
from django.db import models
from django.db.models.signals import pre_save
from ecommerce.utils import unique_slug_generator
from django.urls import reverse


PRODUCT_AVAILABILITY = (
			('OUT', "Out of Stok"),
			('IN', 'In Stock')
	)

 

class Product(models.Model):
	title = models.CharField(max_length=200)
	price = models.FloatField(blank=True, null=True)
	discount_price = models.FloatField(blank=True, null=True)
	description = models.TextField(blank=True, null=True)
	image = models.ImageField(upload_to='product-img/',blank=True, null=True)
	available = models.CharField(max_length=3, choices=PRODUCT_AVAILABILITY,blank=True, null=True)
	slug = models.SlugField(blank=True, null=True)

	def __str__(self):

		return self.title

	def get_absolute_url(self):
		return reverse('products:product_detail', kwargs= {'slug':self.slug})

def slug_generator(sender, instance, *args, **kwargs):

	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator, sender=Product)

products/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.views import generic
from .models import Product
from order.models import Order, OrderProduct
from django.contrib import messages

class HomeListView(generic.ListView):
	template_name = 'products/home.html'
	model = Product
	context_object_name = 'products'

class ProductDetailView(generic.DetailView):
	template_name = 'products/product-detail.html'
	model = Product
	context_object_name = 'product'

def add_to_cart(request, slug):
	product = get_object_or_404(Product, slug=slug)
	order, created= Order.objects.get_or_create(user = request.user)
	queryset = OrderProduct.objects.filter(order= order,
												 product= product, carted= True)
	if queryset.exists():
		messages.info(request, "This product already in your Cart !!")
		return redirect('/')
	else:
		OrderProduct.objects.create(order = order,
										product= product, carted= True)
		messages.info(request, "Product is successfull added your Cart !!")
		return redirect('/')

def remove_from_cart(request, slug):
	product = get_object_or_404(Product, slug=slug)
	order, created= Order.objects.get_or_create(user = request.user)
	queryset = OrderProduct.objects.filter(order= order,
												 product= product, carted= True)
	if queryset.exists():

		query = queryset[0]
		query.delete()
		messages.info(request, "The product is removed !!")
		return redirect('products:product_detail', slug=slug)
	return redirect('/')

def remove_single_product_from_cart(request, slug):
	product = get_object_or_404(Product, slug= slug)
	queryset = OrderProduct.objects.filter(product = product, order__user=request.user, carted= True)
	if queryset.exists():
		q = queryset[0]
		if q.quantity > 1 :
			q.quantity -= 1
			q.save()
			messages.info(request, "The product quantity updated !!")
		else :
			q.delete()
			messages.info(request, "The product is removed !!")
	else:
		messages.info(request, "This Product is not your cart !!")
	return redirect('order:cart_view')

def add_single_product_to_cart(request, slug):
	product = get_object_or_404(Product, slug= slug)
	queryset = OrderProduct.objects.filter(product = product, order__user=request.user, carted= True)
	if queryset.exists():
		query = queryset[0]
		query.quantity +=1
		query.save()
		messages.info(request, "The product quantity is updates!!")
	else:

		messages.info(request, "This Product is not your cart !!")
	return redirect('order:cart_view')
		


	

templates/products/home.html
{% extends 'base/base.html' %}
{% block maincontent %}
<main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for product in products %}
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{product.image.url}}" class="card-img-top"
                  alt="">
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>Shirt</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{product.get_absolute_url}}" class="dark-grey-text">{{product.title}}
                      <span class="badge badge-pill danger-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>${{product.price}}</strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div> 
          {% endfor %}

          <!--Grid column-->
          
          <!--Grid column-->

          <!--Grid column-->
          
          <!--Grid column-->

          <!--Grid column-->
          
          <!--Grid column-->

          <!--Grid column-->
        
          <!--Grid column-->

          <!--Fourth column-->
          
          <!--Fourth column-->

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% include 'base/pagination.html' %}
      <!--Pagination-->

    </div>
  </main>

{% endblock maincontent %}

templates/products/index.html
{% extends 'base.html' %}

{% block content %}


<div>
	{% for product in products %}

		
		<h3><a href="{% url 'product_detail' product.slug %}">{{product.title}}</a></h3>
		<h4>{{product.slug}}</h4>
			{% if product.image %}
		<img src="{{product.image.url}}">
		{% endif %}
		{{product.price}}

	{% endfor %}
	
</div>

{% endblock content %}

templates/products/product-detail.html
{% extends 'base/base.html' %}
{% load check_carted %}

{% block maincontent %}

<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <img src="{{product.image.url}}" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-4">

          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1">Category 2</span>
            </a>
            <a href="">
              <span class="badge blue mr-1">New</span>
            </a>
            <a href="">
              <span class="badge red mr-1">Bestseller</span>
            </a>
          </div>

          <p class="lead">
            {% if not product.discount_price %}
            <span class="mr-1">
              <span>${{product.price}}</span>
            </span>
            {% else %}
            <span class="mr-1">
              <del>${{product.price}}</del>
            </span>
            <span>${{product.discount_price}}</span>
          </p>
          {% endif %}

          <p class="lead font-weight-bold">Description</p>

          <p>{{product.description}}.</p>

          <!-- <form class="d-flex justify-content-left">
             
            <input type="number" value="1" aria-label="Search"  name='quantity' class="form-control" style="width: 100px">
            <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </button>

          </form> -->
          {% if user.is_authenticated and request.user|check:product.slug %}
          <a class="btn btn-warning btn-md my-0 p"  href="{% url 'products:remove-from-cart' product.slug %}">
            remove from cart<i class="fas fa-shopping-cart ml-1"></i></a>
          {% else %}
          <a class="btn btn-primary btn-md my-0 p"  href="{% url 'products:add-to-cart' product.slug %}">
            Add to cart<i class="fas fa-shopping-cart ml-1"></i></a>
          {% endif %}
          
            <a class="btn btn-secondary btn-md my-0 p"  href="{% url 'products:add-to-cart' product.slug %}">
              Buy Now</a>
             

        </div>
        <!--Content-->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <hr>

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 text-center">

        <h4 class="my-4 h4">Additional information</h4>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
          voluptates,
          quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
</main>
{% endblock maincontent %}