ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
   	path('order/', include('order.urls')),
    path('account/', include('account.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
   
]



urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import cart_view, ChechoutProcess, PaymentView
app_name = 'order'

urlpatterns = [
		
			path('cart/',cart_view, name= 'cart_view' ),
			path('checkout/', ChechoutProcess.as_view(), name= 'checkout'),
			path('payment/',PaymentView.as_view(), name='stripe' )

		]

products/urls.py
from django.urls import path
from .views import (HomeListView, ProductDetailView, 
					add_to_cart, remove_from_cart,
					remove_single_product_from_cart,
					add_single_product_to_cart
					
					)
app_name = 'products'
urlpatterns = [

	path('', HomeListView.as_view(), name= 'home'),
	path('detail/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
   	path('add-to-cart/<slug:slug>/', add_to_cart, name= 'add-to-cart'),
   	path('remove-from-cart/<slug:slug>/', remove_from_cart, name= 'remove-from-cart'),
	path('remove-single-product-from-cart/<slug:slug>/', remove_single_product_from_cart, name= 'remove-single'),
	path('add-single-product-to-cart/<slug:slug>/', add_single_product_to_cart, name= 'add-single')

]

order/models.py
from django.db import models
from django.conf import settings
from products.models import Product
from django.utils import timezone
from django_countries.fields import CountryField



class Order(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	carted_date = models.DateTimeField(null=True, blank= True)
	ordered_date = models.DateTimeField(null=True, blank= True)
	address = models.ForeignKey('Address', on_delete= models.SET_NULL, null= True, blank=True)
	def __str__(self):
		return self.user.username
	def get_total(self):
		tottal= 0
		for order_product in self.orderproduct_set.filter(carted= True):
			tottal += order_product.get_final_price()
		return tottal


class OrderProduct(models.Model):
	order = models.ForeignKey(Order, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)
	ordered = models.BooleanField(default=False)
	carted = models.BooleanField(default=False)
	
	

	def __str__(self):
		return f"{self.quantity} of {self.product.title}"

	def get_total_product_price(self):
		return self.product.price * self.quantity
	
	def get_total_product_discount_price(self):
		return self.product.discount_price * self.quantity

	def get_final_price(self):
		if self.product.discount_price :
			return self.get_total_product_discount_price()
		return self.get_total_product_price()

class Address(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	apartment_address = models.CharField(max_length=200)
	street_address = models.CharField(max_length=200)
	country = CountryField(multiple= False)
	zip_code = models.CharField(max_length=10)

	def __str__(self):
		return "%s of %s" %(self.user.username, self.street_address)





	



	

order/forms.py
from django import forms
from .models import Address
from django_countries.widgets import CountrySelectWidget
from django_countries.fields import CountryField

class CheckoutForm(forms.Form):
        street_address = forms.CharField(
                widget=forms.TextInput(attrs={
                        'placeholder':"1234 Main St",'class':"form-control"}))
        apartment_address = forms.CharField(
                required= False, widget=forms.TextInput(
                        attrs={'placeholder':"Apartment or suite", 'class':"form-control" }))
        country = CountryField(
                blank_label= '(slect country)').formfield(
                        widget=CountrySelectWidget( 
                                attrs= {'class':"custom-select d-block w-100" }))
        zip_code  = forms.CharField(
                widget=forms.TextInput(
                        attrs={'class':"form-control" }))   


    

order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Order, OrderProduct, Address
from products.models import Product
from django.views import View
from django.contrib import messages
from django.conf import settings
from .forms import CheckoutForm
import stripe 

# Set your secret key. Remember to switch to your live secret key in production!
# See your keys here: https://dashboard.stripe.com/account/apikeys
stripe.api_key ='sk_test_51HDpedCBNEm08gJKYfP5vpzCx2BkdYTx7F4uQyLdp4z0j3dvfgSN0eDHA1zESGpQDqSVEGfA9fDgj09CuATgCk1E00GLSPxayu'




def cart_view(request):
	try:
		order = Order.objects.filter(user = request.user)[0]
		queryset = order.orderproduct_set.filter(carted= True)
		# p = Product.objects.filter(orderproduct__in= queryset)
		context = {
			'cart':queryset,
			'object':order
		}
		return render(request, 'order/cart.html',context )
	except:
		 messages.warning(request, "you don't have an active order")
		 return redirect('products:home')

	

class ChechoutProcess(View):
	
	def get(self, *args, **kwargs):
		try:
			order = Order.objects.get(user= self.request.user)
			print(order)
			products = order.orderproduct_set.filter(carted= True)
			print(products)
			context={
					'form': CheckoutForm(),
					'order': order,
					'products': products
				}
			return render(self.request, 'checkout.html', context)
		except:
			messages.warning(self.request, "You dont have no active orders")
			return redirect('order:cart_view')

	def post(self, *args, **kwargs):
		form = CheckoutForm(self.request.POST)
		try:
			order = Order.objects.get(user= self.request.user)
			if form.is_valid():
				user = self.request.user
				street_address = form.cleaned_data.get('street_address')
				apartment_address = form.cleaned_data.get('apartment_address')
				country = form.cleaned_data.get('country')
				zip_code = form.cleaned_data.get('zip_code')

				address = Address(
					user = user,
					street_address = street_address,
					apartment_address = apartment_address,
					country = country,
					zip_code = zip_code
				)
				address.save()
				order.address =address
				print(order)
				print('before')
				order.save()
				print('after')
				messages.info(self.request, "you checkout process completed")

				return redirect('order:stripe')
		except:
			messages.info(self.request, "checkout process Failed")
			return redirect('order:cart_view')

class PaymentView(View):

	def get(self, *args, **kwargs):
		order = Order.objects.filter(user = self.request.user)
		context = {
			'order':order
		}

		return render(self.request, 'order/stripe_payment.html', context)
	
	def post(self, *args, **kwargs):
		# Set your secret key. Remember to switch to your live secret key in production!
		# See your keys here: https://dashboard.stripe.com/account/apikeys

		# Token is created using Stripe Checkout or Elements!
		# Get the payment token ID submitted by the form:
		try:

			token = self.request.POST['stripeToken']
			print(token)
			customer = stripe.Customer.create(
				name = self.request.user.username,
				email = self.request.user.email,
				source = token
			)
			order = Order.objects.filter(user = self.request.user)[0]
			orderproduct = order.orderproduct_set.filter(carted= True)
			
			amount = int(order.get_total() * 100)
			print(token)
			stripe.Charge.create(
			customer = customer,
			amount=amount,
			currency='inr',
			description='ecommerce',
			# source = token
			)
			# for product in orderproduct:
			# 	product.ordered = True
			# 	product.carted = False
			# 	product.save()
			orderproduct.update(ordered = True, carted= False)

			messages.info(self.request, "transaction completed!!")
			return redirect('/')
		except Exception as e:
			messages.info(self.request, f"payment incomplete{e}")
			return redirect('/')

		
		

	

templates/order/cart.html
{% extends 'base/base.html' %}

{% block maincontent %}


<div class="container">
	<div class="table-responsive text-nowrap">
	<table class="table">
		<caption>List of users</caption>
		<thead>
		  <tr>
			<th scope="col">NO:</th>
			<th scope="col">Product</th>
			<th scope="col">Price</th>
			<th scope="col">Quantity</th>
			<th scope="col">Total Item Price</th>
		  </tr>
		</thead>
		<tbody>
			{% for orderproduct in cart %}
		  <tr>
			<th scope="row">{{forloop.counter}}</th>
			<td>{{orderproduct.product.title}}</td>
			<td>
				{% if orderproduct.product.discount_price %}
				<span class="mr-1">
					<del>${{orderproduct.product.price}}</del>
				  </span>
				  <span>${{orderproduct.product.discount_price}}</span>
				  {% else %}
				  <span>${{orderproduct.product.price}}</span>
				  {% endif %}
			</td>
			<td>
				<a href="{% url 'products:remove-single' orderproduct.product.slug %}">
				<i class="fas fa-minus mr-2" ></i></a>
				{{orderproduct.quantity}}
			<a href="{% url 'products:add-single' orderproduct.product.slug %}"><i class="fas fa-plus ml-2"></i></a>
			</td>
			<td><b>{{orderproduct.get_final_price}}</b></td>
		  </tr>
		  {% empty %}
		  <tr>
			  <td colspan="5"> You dont have no active orders</td>
		  </tr>
		{% endfor %}
		<tr>
			<td colspan="4"><strong class="float-right">Total Amount</strong></td>
			<td><strong>{{object.get_total}}</strong></td>
		</tr>
		<tr>
			<td colspan="5" ><a href="/" class="btn btn-secondary float-right"> continue to shoppig</a>
				<a href="{% url 'order:checkout' %}" class="btn btn-warning float-right mr-2"> Checkout process</a>
			
			</td>
		</tr>
		</tbody>
	  </table>
	
</div>
</div>

{% endblock maincontent %}

templates/order/stripe_payment.html
  

  
  <style>
    /**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;}
  </style>
<script src="https://js.stripe.com/v3/"></script>

<form method="post" id="payment-form">{% csrf_token %}
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button type="submit">Submit Payment</button>
</form>
<script>// Create a Stripe client.
  var stripe = Stripe('pk_test_51HDpedCBNEm08gJKvlL4kkzrvCw0HIIVmA55zoepfVbQVkyNL6t1OTwmmMqJgCEHx7gwtP1g8fG2RAmsHKCkcNhh00wkUO3MsR');
  
  // Create an instance of Elements.
  var elements = stripe.elements();
  
  // Custom styling can be passed to options when creating an Element.
  // (Note that this demo uses a wider set of styles than the guide below.)
  var style = {
    base: {
      color: '#32325d',
      fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
      fontSmoothing: 'antialiased',
      fontSize: '16px',
      '::placeholder': {
        color: '#aab7c4'
      }
    },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a'
    }
  };
  
  // Create an instance of the card Element.
  var card = elements.create('card', {style: style});
  
  // Add an instance of the card Element into the `card-element` <div>.
  card.mount('#card-element');
  // Handle real-time validation errors from the card Element.
  card.on('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });
  
  // Handle form submission.
  var form = document.getElementById('payment-form');
  form.addEventListener('submit', function(event) {
    event.preventDefault();
  
    stripe.createToken(card).then(function(result) {
      if (result.error) {
        // Inform the user if there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server.
        stripeTokenHandler(result.token);
      }
    });
  });
  
  // Submit the form with the token ID.
  function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);
  
    // Submit the form
    form.submit();
  }
  </script>